<h2>Add User</h2>
<hr /><br />

<style type="text/css">

/* This imageless css button was generated by CSSButtonGenerator.com */
</style>
<form action="<?= base_url() ?>users/add_process" method="post">
        <div class="modal-header">
        
        <?php 
        $success = $this->session->flashdata('success');
        $fail = $this->session->flashdata('fail');
        
        if($success)
            echo '<p><div class="success">'.$success.'</div></p>'; 
        if($fail)
            echo '<p><div class="fail">'.$fail.'</div></p>'; 
        ?>
        </div>
        <div class="modal-body">
            <div class="control-group errlogin_name">
                <label for="inputError" class="control-label">Username</label>
                <div class="controls">
                    <input type="text" name="username" id="username" />
                </div>
            </div>
            <div class="control-group errpassword">
                <label for="inputError" class="control-label">Password</label>
                <div class="controls">
                    <input type="password" name="password" id="password" />
                </div>
            </div>
            <div class="control-group errname">
                <label for="inputError" class="control-label">Name</label>
                <div class="controls">
                    <input type="text" name="name" id="name" />
                </div>
            </div>
            
            
            <div class="control-group">
                <label for="inputError" class="control-label">Users Group</label>
                <div class="controls">
                    <select name="group[]" id="" multiple="">
                        <?php foreach($group[1] as $gr){ ?>
                            <option value="<?php echo $gr['id'] ?>"><?php echo $gr['name'] ?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>
            
            <div class="control-group">
                <label for="inputError" class="control-label">Users Type</label>
                <div class="controls">
                    <select name="user_type" id="user_type" >
                        <?php foreach($userType as $type){ ?>
                            <option value="<?php echo $type['id']; ?>"><?php echo $type['user_type']; ?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>            
            <div class="control-group">
                <label for="inputError" class="control-label">Is active</label>
                <div class="controls">
                    <input type="radio" name="is_active" value="1" checked="" /> Yes &nbsp;&nbsp;
                    <input type="radio" name="is_active" value="0" /> No
                </div>
            </div>
            
            <div class="control-group err_icon">
                <label for="inputError" class="control-label">&nbsp;</label>
                <div class="controls">
                    <input type="submit" class="classname" name="submit" value="submit" /> &nbsp; 
                    <input type="button" class="classname" value="Back" onclick="window.location.href='<?= base_url() ?>users'"/>
                </div>
            </div>
        </div>
    </form>